project:
  type: book

book:
  title: "DO4DS: Lab Solutions"
  author: "Martin Frigaard"
  description: |
    DevOps for Data Science: Lab Solutions
  search: true
  site-url: https://mjfrigaard.github.io/do4ds-labs/
  repo-url: https://github.com/mjfrigaard/do4ds-labs
  chapters:
    - index.qmd 
    - preface.qmd
    - part: lab1.qmd
      chapters:
        - model-basic-py.qmd
        - eda-basic.qmd
    - part: lab2.qmd
      chapters:
        - model-vetiver.qmd
        - model-vetiver-r.qmd
    - part: lab3.qmd
      chapters:
        - py-app-api.qmd
        - r-app-api.qmd
        - plumber2.qmd
    - part: lab4.qmd
      chapters:
        - app-log-py.qmd
        - app-log-r.qmd
    - part: lab5.qmd
      chapters:
        - publish-r-py.qmd
    - part: lab6.qmd
      chapters:
        - py-api-docker.qmd
        - r-api-docker.qmd
        
  appendices:
    - glossary.qmd
    - httr2.qmd
        

format:
  html:
    theme: [cosmo, styles.scss]
    highlight-style: arrow
    date: last-modified
    date-format: iso
    toc: true
    toc-depth: 4
    toc-expand: true
    toc-title: Contents
    toc-location: right
    code-block-bg: "#f8f8f8"
    code-block-border-left: "#02577A"
    code-overflow: scroll
    number-sections: false
    callout-appearance: minimal
    callout-icon: false
    code-link: false
    code-annotations: hover
    dpi: 320
    df-print: kable
    fig-format: retina
    lightbox: true
    #fig-asp: 0.618
    fontsize: 1.055em
    linestretch: 1.35
    fig-width: 7
    fig-height: 5
    engine: knitr
    mermaid:
      theme: default

execute:
  freeze: true
  error: true



