project:
  type: book

book:
  title: "do4ds-labs"
  author: "Martin Frigaard"
  description: |
    DevOps for Data Science: Lab Solutions
  search: true
  site-url: https://mjfrigaard.github.io/do4ds-labs/
  repo-url: https://github.com/mjfrigaard/do4ds-labs
  chapters:
    - index.qmd 
    - preface.qmd
    - part: lab1.qmd
      chapters:
        - eda-basic.qmd
        - model-basic-py.qmd
    - part: lab2.qmd
      chapters:
        - model-vetiver.qmd
    - part: lab3.qmd
      chapters:
        - app-api-r.qmd
        - app-api-py.qmd
        - eda-db.qmd
        - model-db.qmd
        - py-data-load-py.qmd
        - r-data-load-r.qmd

format:
  html:
    theme: [cosmo, styles.scss]
    highlight-style: arrow
    date: last-modified
    date-format: iso
    toc: true
    toc-depth: 4
    toc-expand: true
    toc-title: Contents
    toc-location: right
    code-block-bg: "#f8f8f8"
    code-block-border-left: "#02577A"
    code-overflow: scroll
    number-sections: false
    callout-appearance: minimal
    callout-icon: false
    code-link: false
    code-annotations: hover
    dpi: 320
    df-print: kable
    fig-format: retina
    #fig-asp: 0.618
    fontsize: 1.055em
    linestretch: 1.35
    fig-width: 7
    fig-height: 5
    engine: knitr
    mermaid:
      theme: default

execute:
  freeze: true
  error: true



