project:
  type: book

book:
  title: "DO4DS: Lab Solutions"
  author: "Martin Frigaard"
  description: |
    DevOps for Data Science: Lab Solutions
  search: true
  site-url: https://mjfrigaard.github.io/do4ds-labs/
  repo-url: https://github.com/mjfrigaard/do4ds-labs
  chapters:
    - index.qmd 
    - preface.qmd
    - part: lab01.qmd
      chapters:
        - model-basic-py.qmd
        - eda-basic.qmd
    - part: lab02.qmd
      chapters:
        - model-vetiver.qmd
        - model-vetiver-r.qmd
    - part: lab03.qmd
      chapters:
        - py-app-api.qmd
        - r-app-api.qmd
        - plumber.qmd
        - plumber2.qmd
    - part: lab04.qmd
      chapters:
        - app-log-py.qmd
        - app-log-r.qmd
    - part: lab05.qmd
      chapters:
        - publish-r-py.qmd
    - part: lab06.qmd
      chapters:
        - py-api-docker.qmd
        - r-api-docker.qmd
    - part: lab07.qmd
      chapters:
        - start-aws.qmd  
        - aws-ec2.qmd
        - s3-data.qmd
        - gha-s3.qmd
    - part: lab08.qmd
      chapters:
        - server-login.qmd
    - part: lab09.qmd
      chapters:
        - linux-users.qmd
    - part: lab10.qmd
      chapters:
        - install-apps.qmd
    - part: lab11.qmd
      chapters:
        - instance-size.qmd
    - part: lab12.qmd
      chapters:
        - accessibility.qmd
    - part: lab13.qmd
      chapters:
        - configure-dns.qmd
    - part: lab14.qmd
      chapters:
        - configure-ssl.qmd
        
  appendices:
    - glossary.qmd
    - httr2.qmd
    - plumb.qmd
        

format:
  html:
    theme: [cosmo, styles.scss]
    highlight-style: arrow
    date: last-modified
    date-format: iso
    toc: true
    toc-depth: 4
    toc-expand: true
    toc-title: Contents
    toc-location: right
    code-block-bg: "#faf8f2"
    code-block-border-left: "#2A6F77"
    code-overflow: scroll
    number-sections: false
    callout-appearance: minimal
    callout-icon: false
    code-link: false
    code-annotations: hover
    dpi: 320
    df-print: kable
    fig-format: retina
    lightbox: true
    #fig-asp: 0.618
    fontsize: 1.055em
    linestretch: 1.35
    fig-width: 7
    fig-height: 5
    engine: knitr
    mermaid:
      theme: default

execute:
  freeze: true
  error: true



