# Welcome! {.unnumbered}

Welcome to my lab solutions for Alex K Gold’s [DevOps for Data Science](https://do4ds.com/). 

If you'd like a print version of Alex's book, it's available as part of [Chapman & Hall’s R Series](https://www.routledge.com/Chapman--HallCRC-The-R-Series/book-series/CRCTHERSER). 

## Praise for do4ds

> "*If there's a book that you want to read, but it hasn't been written yet, then you must write it.*" - [Toni Morrison](https://www.goodreads.com/quotes/321-if-there-s-a-book-that-you-want-to-read-but)

I discovered [DevOps for Data Science (do4ds)](https://do4ds.com/) by [Alex K Gold](https://alexkgold.space/) at the end of 2022, just as I was starting a new position as a Posit System Administrator with CDC’s [Enterprise Data, Analytics, and Visualization (EDAV)](https://www.cdc.gov/data-modernization/php/technologies/edav.html) platform.[^edav] I’d been an R programmer/Shiny developer for 10+ years, but as a new System Admin, my responsibilities now included (and were not limited to) maintaining, monitoring, updating and improving the Posit services for CDC users.

[DevOps for Data Science](https://do4ds.com/) was ~90% of the book I wanted to read, and completing the lab solutions allowed me to address the remaining 10%. 


[^edav]: EDAV houses multiple enterprise data science products (Databricks, Power BI, Tableau, SAS Viya, etc.), including Posit Workbench, Connect, and Package Manager. Read more about EDAV and the [Data Modernization Initiative](https://www.cdc.gov/data-modernization/php/about/dmi.html).



## Other great resources 

I also regularly checked and referenced additional topics from the following resources: 

1. [The Linux Command Line](https://linuxcommand.org/tlcl.php) by William Shotts    
2. [How Linux Works: what every superuser show know](https://a.co/d/4YVb01t) by Brian Ward    
3. [The Linux programming interface: a Linux and UNIX system programming handbook](https://a.co/d/dhKUgR4) by Michael Kerrisk.

