# <em>Modeling in Python</em> {#sec-model-basic-py}

The `model-basic-py.qmd` file creates a model using Python's `palmerpenguins`, `numpy`, `pandas`, and `scikit-learn` libraries. 

<details>
  <summary><strong>View model-basic-py.qmd</strong></summary>
  
<br>
  
```{r}
#| label: print-eda-basic-qmd
#| echo: false
library(readr)
readr::read_lines("_labs/lab1/model-basic-py.qmd") |> 
  base::noquote() |> 
  writeLines()
```

</details>

I've added the `reticulate` code below to run this code in Quarto. 

```{r}
#| results: hide
#| message: false 
#| warning: false
library(reticulate)
use_virtualenv("myenv", required = TRUE)
virtualenv_install(
  envname = "myenv", 
  packages = c("palmerpenguins", "pandas", "numpy", 
               "scikit-learn", "jupyter"))
```


```{python}
#| eval: true
from palmerpenguins import penguins
from pandas import get_dummies
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn import preprocessing
```

```{python}
#| eval: true
df = penguins.load_penguins().dropna()

df.head(3)
```

```{python}
#| eval: true
X = get_dummies(df[['bill_length_mm', 'species', 'sex']], drop_first = True)
y = df['body_mass_g']

model = LinearRegression().fit(X, y)
```

```{python}
#| eval: true
print(f"R^2 {model.score(X,y)}")
print(f"Intercept {model.intercept_}")
print(f"Columns {X.columns}")
print(f"Coefficients {model.coef_}")
```

