# <em>`plumber2`</em> {.unnumbered}

```{r}
#| label: common
#| include: false
source("_common.R")
```

```{r}
#| label: co_box_rev
#| echo: false
#| results: asis
#| eval: true
co_box(
  color = "o",
  look = "default", 
  hsize = "1.25", 
  size = "1.00", 
  header = "Caution", 
  fold = FALSE,
  contents = "This section is being revised. Thank you for your patience."
)
```

Since the original writing of [do4ds](https://do4ds.com/), [`plumber`](https://www.rplumber.io/) underwent an upgrade to [`plumber2`](https://plumber2.posit.co/). I've summarized the changes to the API (along with the inclusion of the [`logger` package](https://daroczig.github.io/logger/)) below. 

## Model 



```{mermaid}
%%{init: {'theme': 'neutral', 'look': 'handDrawn', 'themeVariables': { 'fontFamily': 'monospace'}}}%%

graph LR
    subgraph "plumber Documentation"
        A1(["#* @get /ping"])
        A2[#* Endpoint function]
        A3("Basic Swagger docs")
    end
    
    subgraph "plumber2 Documentation"
        B1(["#* @get /ping<br/>#* @tag Health<br/>#* @response 200 Description<br/>#* @serializer unboxedJSON"])
        B2[#* Enhanced function with metadata]
        B3(["Rich Swagger UI<br/>with tags, responses,<br/>detailed descriptions"])
    end
    
    A1 --> A2
    A2 --> A3
    
    B1 --> B2
    B2 --> B3
    
    A3 -.->|"<em>Upgrade to</em>"| B3
```