# <em>Python App API</em> {.unnumbered}

```{r}
#| label: common
#| include: false
source("_common.R")
```

```{r}
#| label: co_box_rev
#| echo: false
#| results: asis
#| eval: true
co_box(
  color = "o",
  look = "default", 
  hsize = "1.25", 
  size = "1.00", 
  header = "Caution", 
  fold = FALSE,
  contents = "This section is being revised. Thank you for your patience."
)
```

In [lab 2](lab2.qmd), we created a Python model with `scikit-learn`, converted it into a `VetiverModel`, saved it in a `pins` board folder, then created a `VetiverAPI`:

```{mermaid}
%%| fig-cap: 'Our Python model pipeline'
%%| fig-align: center
%%{init: {'theme': 'neutral', 'look': 'handDrawn', 'themeVariables': { 'fontFamily': 'monospace', "fontSize":"16px"}}}%%
graph LR
    subgraph DataPrep["<strong>Data Preparation</strong>"]
        Penguins["<code>penguins</code><br>data"] --> DuckDB["put in<br><code>duckdb</code>"]
        DuckDB
    end
    
    subgraph ModTrain["<strong>Linear Regression</strong>"]
        DuckDB --> LinReg["create <code>scikit-learn</code><br>model"]
        LinReg
    end
    
    subgraph MLOps["<strong>MLOps</strong>"]
        LinReg --> VetMod["create<br><code>VetiverModel()</code>"]
        VetMod --> Pins["save to<br><code>pins</code> board"]
        Pins --> VetAPI["create<br><code>VetiverAPI()</code>"]
    end
    
    style ModTrain fill:#e1f5fe
    style MLOps fill:#f3e5f5
    style VetAPI fill:#e8f5e8
```

## Initial launch

## API 

### Start the API

## App 

### Reactive values 

### Predictions

## Verify

### Back in the API 

