# <em>R App API</em> {.unnumbered}

```{r}
#| label: common
#| include: false
source("_common.R")
```

```{r}
#| label: co_box_rev
#| echo: false
#| results: asis
#| eval: true
co_box(
  color = "o",
  look = "default", 
  hsize = "1.25", 
  size = "1.00", 
  header = "Caution", 
  fold = FALSE,
  contents = "This section is being revised. Thank you for your patience."
)
```

## app-api.R {#sec-app-api-r}

<details>
  <summary>Expand to view app-api.R</summary>

```{r}
#| label: print-app-api-R
#| echo: false
library(readr)
readr::read_lines("_labs/lab3/app-api.R") |> 
  base::noquote() |> 
  writeLines()
```

</details>


## r-data-load.R {#sec-r-data-load-r}

<details>
  <summary>Expand to view r-data-load.R</summary>

```{r}
#| label: print-r-data-load-R
#| echo: false
#| code-overflow: wrap
library(readr)
readr::read_lines("_labs/lab3/r-data-load.R") |> 
  base::noquote() |> 
  writeLines()
```

</details>

## eda-db.qmd {#sec-eda-db.qmd}

<details>
  <summary>Expand to view eda-db.qmd</summary>
  
```{r}
#| label: print-eda-db.qmd
#| echo: false
library(readr)
readr::read_lines("_labs/lab3/eda-db.qmd") |> 
  base::noquote() |> 
  writeLines()
```

</details>